### ISSUE TITLE
getVariables can be called even when getPause returns true

### ISSUE THREAD

**Issue by scamden** [jotai-labs/jotai-urql#19]
We frequently use getPause to stop a jotai-urql atom from querying when one of our input variables is null. The main query callback doesn't call getVariables when getPause returns true in this case, but the reexecute one does, which triggers invariants for us sometimes if someone wanted to assert that what they validated in getPause is true within getVariables. 

Would be great to only call getVariables in getPause is not true.

**Comment by RIP21** [comment]
I think this is already solved and actually published in the latest version:
https://github.com/jotaijs/jotai-urql/pull/15

Unless I don't understand the problem correctly.

**Comment by scamden** [comment]
yep whoops! we were one patch version behind. i verified the latest version fixes this for us. Thanks for being a step ahead!
