### ISSUE TITLE
resetting the urql client in jotai

### ISSUE THREAD

**Issue by wcastand** [jotai-labs/jotai-urql#21]
from what i understood from the documentation, `useHydrateAtoms` will not update the client if it changes. our use case is when the user disconnect, we create a new client to clear the urql's cache.

did i misunderstood that part and it would work when i reset/re-create the urql client?

Otherwise is there a way currently to support that use case? knowing that re-creating the client is the urql recommend to handle logging out users and clearing cache.

**Comment by dai-shi** [comment]
can you share a short code snippet to illustrate the problem?

**Comment by RIP21** [comment]
@wcastand having limited understanding of your use case. I think, if you want to reset the state, you just recreate urql client and set it to the `clientAtom` that is being exported by the `jotai-urql`.
This should in return trigger a whole lot of operations for all dependent atoms (which are all the atoms of `jotai-urql`).

If I remember correctly (I've not been using Jotai in production for more than a year), `useHydrateAtoms` gets called only once and never again. Unless the component is unmounted and mounted again.

So, yeah, if you need to reset it, just `const setClient = useSetAtom(clientAtom)` and then `setClient(createClient(...)`) somewhere.

**Comment by wcastand** [comment]
Yeah I figured hydrate would not work. I will give it a try next week and see what happens 

Thanks for all the help and sorry I didn't pass an example was busy on Saturday :)
